---
name: Check updates

on:
  schedule:
    - cron: '0 0 1,15 * *'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  check_versions:
    name: Yarn
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Print outdated dependencies
        run: yarn outdated || true
      - name: Update versions
        run: yarn upgrade --latest
      - name: Compile
        run: |
          rm yarn.lock
          yarn install
          yarn run build
        shell: bash
      - name: Check local changes
        id: git-diff
        run: |
          changed_files=$(git status --porcelain --untracked-files=no | wc -l)
          echo '::set-output name=count::'$changed_files
        shell: bash
      - name: Increase version
        if: ${{ steps.git-diff.outputs.count > 0 }}
        run: yarn version --patch --no-git-tag-version
      - name: Create PR
        if: ${{ steps.git-diff.outputs.count > 0 }}
        uses: peter-evans/create-pull-request@v3.6.0
        with:
          author: ${{ github.actor }} <${{ github.actor }}@gmail.com>
          base: main
          body: |
            ## Description
            Bump dependencies
            ## Workflow
            - _Name:_ ${{ github.workflow }}
            - _Run ID:_ ${{ github.run_id }}
            - _Run Number:_ ${{ github.run_number }}
          branch: bump/patch
          branch-suffix: timestamp
          commit-message: 'Bump dependencies by "${{ github.workflow }} #${{ github.run_number }}"'
          delete-branch: true
          labels: dependencies
          reviewers: ${{ github.actor }}
          title: 'Bump dependencies by "${{ github.workflow }} #${{ github.run_number }}"'
