---
name: Check updates

on:
  schedule:
    - cron: '0 0 1,15 * *'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  check_versions:
    name: Yarn
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Print outdated dependencies
        run: yarn outdated || true
      - name: Update versions
        run: yarn upgrade --latest
      - name: Compile
        run: |
          rm -f yarn.lock
          yarn install
          yarn run build
        shell: bash
      - name: Check local changes
        id: git-diff
        run: |
          changed_files=$(git status --porcelain --untracked-files=no | wc -l)
          echo '::set-output name=count::'$changed_files
        shell: bash
      - name: Increase version
        if: ${{ steps.git-diff.outputs.count > 0 }}
        run: yarn version --patch --no-git-tag-version
      - name: Create PR
        if: ${{ steps.git-diff.outputs.count > 0 }}
        uses: peter-evans/create-pull-request@v3.6.0
        env:
          HUSKY: 0
        with:
          assignees: ${{ github.actor }}
          base: main
          body: |
            ## Description

            Bump dependencies

            ## Workflow

            - Name: ${{ github.workflow }}
            - Run ID: ${{ github.run_id }}
            - Run Number: ${{ github.run_number }}

            _Auto-generated by [peter-evans/create-pull-request][1]_

            [1]: https://github.com/peter-evans/create-pull-request
          branch: bump/patch
          branch-suffix: timestamp
          commit-message: 'Bump dependencies by "${{ github.workflow }} #${{ github.run_number }}"'
          committer: GitHub <noreply@github.com>
          delete-branch: true
          labels: dependencies
          reviewers: ${{ github.actor }}
          title: 'Bump dependencies by "${{ github.workflow }} #${{ github.run_number }}"'
