---
name: Test providers

on: # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - .github/workflows/test-providers.yml
      - dist/**
      - src/**
      - action.yml
  push:
    branches:
      - main

defaults:
  run:
    shell: sh

jobs:
  test-providers:
    name: ${{ matrix.provider }} (${{ matrix.api_key == '' && 'Free' || 'Paid' }})
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        source: ["Love"]
        include:
          - provider: "deepl"
            lang: "en-uk"
            expected: "Любов"
            api_key: "DEEPL_API_KEY" # pragma: allowlist secret
          - provider: "google"
            lang: "en-hr"
            expected: "Ljubav"
          - provider: "linguatools"
            lang: "en-de"
            expected: "Love"
          - provider: "mymemory"
            lang: "en|sw"
            expected: "Mfano"
          - provider: "mymemory"
            lang: "en|pt"
            expected: "Amor"
            api_key: "MYMEMORY_API_KEY" # pragma: allowlist secret
          - provider: "funtranslations"
            lang: "klingon"
            expected: "Parmaq"
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Translate (${{ matrix.provider }}, ${{ matrix.lang }})
        uses: ./
        id: result
        with:
          provider: ${{ matrix.provider }}
          lang: ${{ matrix.lang }}
          source: ${{ matrix.source }}
          api_key: "${{ matrix.api_key == '' && '' || secrets[matrix.api_key] }}"
      - name: Validate ${{ matrix.provider }} translation result
        run: |
          echo "'${{ matrix.source }}' has been translated to '${{ steps.result.outputs.text }}'"
          [ "${{ steps.result.outputs.text }}" = "${{ matrix.expected }}" ] || exit 1;
